INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','19','Guajará-Mirim','RONDÔNIA','RO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','27','ALTO ALEGRE DOS PARECIS','RONDÔNIA','RO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','35','Porto Velho','RONDÔNIA','RO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','43','BURITIS','RONDÔNIA','RO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','51','Ji-Paraná','RONDÔNIA','RO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','60','CHUPINGUAIA','RONDÔNIA','RO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','78','Ariquemes','RONDÔNIA','RO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','86','CUJUBIM','RONDÔNIA','RO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','94','Cacoal','RONDÔNIA','RO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','108','Nova União','RONDÔNIA','RO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','116','Pimenta Bueno','RONDÔNIA','RO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','124','PARECIS','RONDÔNIA','RO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','132','Vilhena','RONDÔNIA','RO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','140','PIMENTEIRAS DO OESTE','RONDÔNIA','RO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','159','Jaru','RONDÔNIA','RO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','167','PRIMAVERA DE RONDÔNIA','RONDÔNIA','RO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','175','Ouro Preto do Oeste','RONDÔNIA','RO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','183','SAO FELIPE D´OESTE','RONDÔNIA','RO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','191','Presidente Médici','RONDÔNIA','RO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','205','SÃO FRANCISCO DO GUAPORÉ','RONDÔNIA','RO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','213','Costa Marques','RONDÔNIA','RO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','221','TEIXEIROPOLIS','RONDÔNIA','RO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','230','Colorado do Oeste','RONDÔNIA','RO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','248','VALE DO ANARI','RONDÔNIA','RO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','256','ESPIGAO D´Oeste','RONDÔNIA','RO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','264','AMAJARI','RORAIMA','RR');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','272','Cerejeiras','RONDÔNIA','RO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','280','CANTÁ','RORAIMA','RR');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','299','Rolim de Moura','RONDÔNIA','RO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','302','CAROEBE','RORAIMA','RR');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','310','Caldazinha','GOIÁS','GO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','329','IRACEMA','RORAIMA','RR');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','337','Alta Florest D´Oeste','RONDÔNIA','RO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','345','PACARAIMA','RORAIMA','RR');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','353','Alvorada D´Oeste','RONDÔNIA','RO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','361','Rorainopolis','RORAIMA','RR');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','370','Cabixi','RONDÔNIA','RO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','388','UIRAMUTA','RORAIMA','RR');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','396','Machadinho D´Oeste','RONDÔNIA','RO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','400','ANAPU','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','418','Nova Brasilândia D´Oeste','RONDÔNIA','RO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','426','BANNACH','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','434','Santa Luzia D´Oeste','RONDÔNIA','RO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','442','BELTERRA','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','450','SAO MIGUEL DO GUAPORE','RONDÔNIA','RO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','469','CACHOEIRA DO PIRIA','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','477','NOVA MAMORE','RONDÔNIA','RO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','485','CANAA DOS CARAJAS','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','493','Jesúpolis','GOIÁS','GO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','507','CURUA','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','515','Professor Jamil','GOIÁS','GO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','523','FLORESTA DO ARAGUAIA','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','531','Santo Antônio de Goiás','GOIÁS','GO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','540','Marituba','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','558','Cocalzinho de Goiás','GOIÁS','GO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','566','NOVA IPIXUNA','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','574','Terezópolis de Goiás','GOIÁS','GO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','590','Uirapuru','GOIÁS','GO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','612','Buritinópolis','GOIÁS','GO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','620','QUATIPURU','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','639','Buriti de Goiás','GOIÁS','GO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','655','Guaraita','GOIÁS','GO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','671','Vila Boa','GOIÁS','GO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','698','Inaciolândia','GOIÁS','GO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','701','VITORIA DO JARI','AMAPÁ','AP');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','710','Aparecida do Rio Doce','GOIÁS','GO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','736','Chapadão do Céu','GOIÁS','GO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('0','744','uruana de minas','MINAS GERAIS','MG');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','752','Perolândia','GOIÁS','GO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','760','MARATAIZES','ESPÍRITO SANTO','ES');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','779','Cidade Ocidental','GOIÁS','GO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','795','Montividiu do Norte','GOIÁS','GO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','817','Castelândia','GOIÁS','GO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','833','Santo Antônio da Barra','GOIÁS','GO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','850','Alto Horizonte','GOIÁS','GO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','868','LAVANDEIRA','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','876','Nova Iguaçú de Goiás','GOIÁS','GO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','892','Cotriguacu','MATO GROSSO','MT');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','906','MONTE SANTO DO TOCANTINS','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','914','Planalto da Serra','MATO GROSSO','MT');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','930','São Pedro da Cipa','MATO GROSSO','MT');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','957','Pontal do Araguaia','MATO GROSSO','MT');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','965','SANTA RITA DO TOCANTINS','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','973','Querência','MATO GROSSO','MT');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','990','Ribeirãozinho','MATO GROSSO','MT');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1015','Porto Estrela','MATO GROSSO','MT');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1023','TUPIRAMA','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1031','Nova Marilândia','MATO GROSSO','MT');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1040','AGUA DOCE DO MARANHAO','MARANHÃO','MA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1058','Brasiléia','ACRE','AC');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1066','ALTO ALEGRE DO MARANHAO','MARANHÃO','MA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1074','Cruzeiro do Sul','ACRE','AC');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1082','ALTO ALEGRE DO PINDARE','MARANHÃO','MA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1090','Mâncio Lima','ACRE','AC');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1112','Nova Maringá','MATO GROSSO','MT');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1120','APICUM-AÇU','MARANHÃO','MA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1139','Feijó','ACRE','AC');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1147','Araguanã','MARANHÃO','MA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1155','Santo Afonso','MATO GROSSO','MT');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1163','BACABEIRA','MARANHÃO','MA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1171','Nova Bandeirantes','MATO GROSSO','MT');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1180','BACURITUBA','MARANHÃO','MA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1198','Nova Monte Verde','MATO GROSSO','MT');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1210','Nova Guaritá','MATO GROSSO','MT');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1236','Santa Carmen','MATO GROSSO','MT');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1252','Tabapora','MATO GROSSO','MT');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1260','BOA VISTA DO GURUPI','MARANHÃO','MA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1279','Alto Boa Vista','MATO GROSSO','MT');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1287','BOM JESUS DAS SELVAS','MARANHÃO','MA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1295','Canabrava do Norte','MATO GROSSO','MT');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1317','Confresa','MATO GROSSO','MT');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1333','São José do Xingu','MATO GROSSO','MT');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1341','BURITICUPU','MARANHÃO','MA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1350','Glória D´Oeste','MATO GROSSO','MT');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1368','BURITIRANA','MARANHÃO','MA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1376','Lambári D´Oeste','MATO GROSSO','MT');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1392','Rio Branco','ACRE','AC');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1414','Alcinópolis','MATO GROSSO DO SUL','MS');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1430','Nova Alvorada do Sul','MATO GROSSO DO SUL','MS');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1449','CENTRAL DO MARANHÃO','MARANHÃO','MA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1457','Sena Madureira','ACRE','AC');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1473','Tarauacá','ACRE','AC');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1490','Xapuri','ACRE','AC');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1511','Plácido de Castro','ACRE','AC');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1520','CONCEICAO DO LAGO-ACU','MARANHÃO','MA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1538','Senador Guiomard','ACRE','AC');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1554','Manoel Urbano','ACRE','AC');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1570','Assis Brasil','ACRE','AC');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1597','Novo Horizonte do Sul','MATO GROSSO DO SUL','MS');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1600','Formosa da Serra Negra','MARANHÃO','MA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1619','Japorã','MATO GROSSO DO SUL','MS');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1635','Laguna Carapã','MATO GROSSO DO SUL','MS');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1651','Angico','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1660','GOVERNADOR NEWTON BELLO','MARANHÃO','MA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1678','Aragominas','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1686','Governador Nunes Freire','MARANHÃO','MA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1694','Araguanã','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1708','IGARAPE DO MEIO','MARANHÃO','MA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1716','Cachoeirinha','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1732','Campos Lindos','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1740','ITINGA DO MARANHAO','MARANHÃO','MA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1759','Carmolândia','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1775','Carrasco Bonito','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1791','Darcinópolis','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1813','Esperantina','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1821','LAGOA DO MATO','MARANHÃO','MA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1830','Maurilândia do Tocantins','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1856','Mosquito','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1872','Muricilândia','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1899','Palmeirante','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1902','MARACAÇUMÉ','MARANHÃO','MA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1910','Pau D´Arco','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1937','Riachinho','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1945','MARANHAZINHO','MARANHÃO','MA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1953','Santa Fé do Araguaia','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1970','São Bento do Tocantins','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','1996','São Miguel do Tocantins','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2011','Novo Airão','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2038','Anori','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2054','Atalaia do Norte','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2062','PAULINO NEVES','MARANHÃO','MA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2070','Autazes','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2089','Pedro do Rosário','MARANHÃO','MA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2097','Barcelos','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2100','PERITORO','MARANHÃO','MA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2119','Barreirinha','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2127','PORTO RICO DO MARANHÃO/MARANHÃO E PINHEI','MARANHÃO','MA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2135','Benjamin Constant','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2151','Boca do Acre','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2178','Borba','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2186','RAPOSA','MARANHÃO','MA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2194','Canutama','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2216','Carauari','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2232','Careiro','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2240','Santana do Maranhão','MARANHÃO','MA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2259','Coari','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2267','SANTO AMARO DO MARANHÃO','MARANHÃO','MA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2275','Codajás','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2283','SAO DOMINGOS DO AZEITAO','MARANHÃO','MA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2291','Eirunepé','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2305','SÃO FRANCISCO DO BREJÃO','MARANHÃO','MA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2313','Envira','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2330','Fonte Boa','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2348','SAO JOAO DO PARAISO','MARANHÃO','MA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2356','Humaitá','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2372','Santa Isabel do Rio Negro','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2399','Ipixuna','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2410','Itacoatiara','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2437','Itapiranga','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2453','Japurá','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2470','Juruá','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2488','SATUBINHA','MARANHÃO','MA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2496','Jutai','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2518','Lábrea','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2526','SENADOR LA ROCQUE','MARANHÃO','MA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2534','Manacapuru','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2542','SERRANO DO MARANHÃO','MARANHÃO','MA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2550','Manaus','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2577','Manicoré','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2585','TRIZIDELA DO VALE','MARANHÃO','MA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2593','Maraã','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2615','Maués','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2631','Nhamundá','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2640','VILA NOVA DOS MARTÍRIOS','MARANHÃO','MA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2658','Nova Olinda do Norte','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2666','ACAUA','PIAUÍ','PI');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2674','Novo Aripuanã','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2682','ALVORADA DO GURGUEIA','PIAUÍ','PI');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2690','Parintins','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2704','ASSUNCAO DO PIAUI','PIAUÍ','PI');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2712','Pauini','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2739','Santo Antônio do Içá','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2747','BELA VISTA DO PIAUI','PIAUÍ','PI');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2755','São Paulo de Olivença','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2771','Silves','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2798','Tapauá','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2801','BOA HORA','PIAUÍ','PI');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2810','Tefé','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2836','São Gabriel da Cachoeira','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2852','Urucará','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2860','CAJAZEIRAS DO PIAUI','PIAUÍ','PI');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2879','Urucurituba','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2895','Alvarães','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2909','CAMPO ALEGRE DO FIDALGO','PIAUÍ','PI');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2917','Amatura','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2925','Campo Grande do Piaui','PIAUÍ','PI');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2933','Anama','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2950','Beruri','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2976','Boa Vista do Ramos','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','2992','Caapiranga','AMAZONAS','AM');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3018','Boa Vista','RORAIMA','RR');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3034','Caracaraí','RORAIMA','RR');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3050','Alto Alegre','RORAIMA','RR');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3077','Bonfim','RORAIMA','RR');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3093','Mucajaí','RORAIMA','RR');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3107','CURRALINHO','PIAUÍ','PI');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3115','Normandia','RORAIMA','RR');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3131','São João da Baliza','RORAIMA','RR');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3158','São Luiz','RORAIMA','RR');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3174','Mateiros','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3182','GEMINIANO','PIAUÍ','PI');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3212','Novo Jardim','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3220','ILHA GRANDE DO PIAUI','PIAUÍ','PI');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3239','Rio da Conceição','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3255','Taipas do Tocantins','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3263','JOAO COSTA','PIAUÍ','PI');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3271','Cariri do Tocantins','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3298','Jaú do Tocantins','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3310','Sandolândia','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3336','São Salvador do Tocantins','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3344','JUREMA','PIAUÍ','PI');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3352','Sucupira','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3379','Abreulândia','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3395','Brasilândia do Tocantins','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3409','Lagoa do Piauí','PIAUÍ','PI');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3417','Bom Jesus do Tocantins','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3425','LAGOA DO SÍTIO','PIAUÍ','PI');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3433','Centenário','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3441','MADEIRO','PIAUÍ','PI');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3450','Fortaleza do Tabocão','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3476','Itapiratins','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3484','MILTON BRANDAO','PIAUÍ','PI');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3492','Juarina','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3514','Lajeado','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3530','Lagoa do Tocantins','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3549','MURICI DOS PORTELAS','PIAUÍ','PI');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3557','Piraquê','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3573','Recursolândia','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3590','Rio dos Bois','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3611','Santa Maria do Tocantins','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3620','PAJEU DO PIAUI','PIAUÍ','PI');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3638','São Félix do Tocantins','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3654','Tupiratins','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3670','Lagoa da Confusão','TOCANTIS','TO');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3689','PEDRO LAURENTINO','PIAUÍ','PI');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3697','Santa Bárbara do Pará','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3719','Santa Luzia do Pará','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3727','PORTO ALEGRE DO PIAUI','PIAUÍ','PI');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3735','Terra Alta','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3751','Abel Figueiredo','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3778','Eldorado dos Carajás','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3794','Palestina do Pará','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3816','São Domingos do Araguaia','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3824','SAO GONCALO DO GURGUEIA','PIAUÍ','PI');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3832','Água Azul do Norte','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3859','Cumaru do Norte','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3875','Pau D´Arco','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3891','Aurora do Pará','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3913','Nova Esperança do Piriá','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3921','SÃO MIGUEL DA BAIXA GRANDE','PIAUÍ','PI');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3930','São João de Piribas','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3956','Tailândia','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3972','Tucumã','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','3999','Uruará','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4014','Abaetetuba','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4030','Acará','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4057','Afuá','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4073','Alenquer','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4081','VILA NOVA DO PIAUI','PIAUÍ','PI');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4090','Almeirim','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4103','WALL FERRAZ','PIAUÍ','PI');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4111','Altamira','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4138','Anajás','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4154','Ananindeua','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4162','FERNANDO PEDROZA','RIO GRANDE DO NORTE','RN');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4170','Augusto Corrêa','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4189','Itaja','RIO GRANDE DO NORTE','RN');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4197','Aveiro','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4200','MAJOR SALES','RIO GRANDE DO NORTE','RN');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4219','Bagre','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4235','Baião','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4243','SANTA MARIA','RIO GRANDE DO NORTE','RN');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4251','Barcarena','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4278','Belém','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4294','Benevides','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4316','Bonito','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4332','Bragança','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4359','BREVES','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4375','Bujaru','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4391','CACHOEIRA DO ARARI','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4405','ALCANTIL','PARAÍBA','PB');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4413','Cametá','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4421','ALGODÃO DE JANDAIRA','PARAÍBA','PB');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4430','Capanema','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4456','Capitão Poco','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4464','Aparecida','PARAÍBA','PB');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4472','Castanhal','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4480','Areia de Baraunas','PARAÍBA','PB');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4499','CHAVES','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4510','Colares','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4529','BARAÚNA','PARAÍBA','PB');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4537','Conceição do Araguaia','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4553','CURRALINHO','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4561','BERNARDINO BATISTA','PARAÍBA','PB');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4570','Curuçá','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4596','FARO','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4600','CACIMBAS','PARAÍBA','PB');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4618','GURUPÁ','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4626','CAJAZEIRINHAS','PARAÍBA','PB');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4634','Igarapé-Açu','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4642','CAPIM','PARAÍBA','PB');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4650','Igarapé-Miri','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4677','Inhangapi','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4685','CASSERENGUE','PARAÍBA','PB');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4693','Iritúia','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4715','Itaituba','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4723','COXIXOLA','PARAÍBA','PB');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4731','Itupiranga','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4758','Jacunda','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4766','CURRAL DE CIMA','PARAÍBA','PB');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4774','JURUTI','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4782','DAMIÃO','PARAÍBA','PB');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4790','Limoeiro do Ajuru','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4804','GADO BRAVO','PARAÍBA','PB');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4812','Magalhães Barata','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4839','Marabá','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4847','MARCAÇÃO','PARAÍBA','PB');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4855','Maracanã','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4863','Marizópolis','PARAÍBA','PB');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4871','Marapanim','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4898','MELGACO','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4910','Mocajuba','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4928','MATUREIA','PARAÍBA','PB');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4936','Moju','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4952','MONTE ALEGRE','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4960','POÇO DANTAS','PARAÍBA','PB');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4979','MUANA','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','4995','Nova Timboteua','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5002','PEDRO RÉGIS','PARAÍBA','PB');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5010','OBIDOS','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5029','RIACHÃO','PARAÍBA','PB');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5037','Oeiras do Pará','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5045','RIAÇHÃO DO BACAMARTE','PARAÍBA','PB');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5053','ORIXIMINA','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5061','RIAÇHÃO DO POÇO','PARAÍBA','PB');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5070','Ourém','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5088','RIACHO DE SANTO ANTONIO','PARAÍBA','PB');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5096','Paragominas','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5100','SANTA CECILIA','PARAÍBA','PB');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5118','Peixe-Boi','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5134','PONTE DE PEDRAS','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5142','SANTAREM','PARAÍBA','PB');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5150','PORTEL','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5177','Porto de Moz','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5185','SAO BENTINHO','PARAÍBA','PB');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5193','PRAINHA','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5207','SAO DOMINGOS DO CARIRI','PARAÍBA','PB');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5215','Primavera','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5231','Salinópolis','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5240','SAO FRANCISCO','PARAÍBA','PB');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5258','SALVATERRA','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5274','SANTA CRUZ DO ARARI','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5282','SÃO JOSÉ DE PRINCESA','PARAÍBA','PB');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5290','Santa Isabel do Pará','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5304','SÃO JOSÉ DO BREJO DA CRUZ','PARAÍBA','PB');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5312','Santa Maria do Pará','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5339','Santana do Araguaia','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5355','SANTAREM','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5371','Santarém Novo','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5380','TENÓRIO','PARAÍBA','PB');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5398','Santo Antônio do Tauá','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5410','São Caetano de Odivelas','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5436','São Domingos do Capim','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5444','ARACOIABA','PERNAMBUCO','PE');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5452','São Félix do Xingu','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5460','CASINHAS','PERNAMBUCO','PE');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5479','São Francisco do Pará','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5495','São João do Araguaia','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5509','Jatobá','PERNAMBUCO','PE');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5517','São Miguel do Guamá','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5525','Lagoa Grande','PERNAMBUCO','PE');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5533','SAO SEBASTIAO DA BOA VISTA','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5550','Senador José Porfírio','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5568','SANTA FILOMENA','PERNAMBUCO','PE');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5576','SOURE','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5584','Tamandare','PERNAMBUCO','PE');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5592','Tomé-Açú','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5606','CAMPESTRE','ALAGOAS','AL');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5614','Tucurui','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5630','Vigia','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5649','ALTO CAPARAO','MINAS GERAIS','MG');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5657','Viseu','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5673','Redenção','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5681','ARICANDUVA','MINAS GERAIS','MG');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5690','Rio Maria','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5703','BERIZAL','MINAS GERAIS','MG');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5711','Xinguara','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5720','BONITO DE MINAS','MINAS GERAIS','MG');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5738','Rondon do Pará','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5754','Bom Jesus do Tocantins','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5762','Bugre','MINAS GERAIS','MG');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5770','Brejo Grande do Araguaia','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5789','CABECEIRA GRANDE','MINAS GERAIS','MG');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5797','Concórdia do Pará','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5800','CAMPO AZUL','MINAS GERAIS','MG');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5819','Curionópolis','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5827','CANTAGALO','MINAS GERAIS','MG');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5835','Dom Eliseu','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5851','Garrafão do Norte','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5860','CATUTI','MINAS GERAIS','MG');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5878','Mãe do Rio','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5886','Chapada Gaúcha','MINAS GERAIS','MG');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5894','Medicilândia','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5908','CONEGO MARINHO DE MINAS','MINAS GERAIS','MG');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5916','Ourilândia do Norte','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5924','Confins','MINAS GERAIS','MG');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5932','Pacajá','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5940','Corrego Fundo','MINAS GERAIS','MG');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5959','Parauapebas','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5967','CRISOLITA','MINAS GERAIS','MG');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5975','Rurópolis','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','5991','Santa Maria das Barreiras','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6009','CURRAL DE DENTRO','MINAS GERAIS','MG');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6017','Amapá','AMAPÁ','AP');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6033','Calcoene','AMAPÁ','AP');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6041','Divisa Alegre','MINAS GERAIS','MG');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6050','Macapá','AMAPÁ','AP');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6076','Mazagão','AMAPÁ','AP');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6084','FRANCISCOPOLIS','MINAS GERAIS','MG');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6092','Oiapoque','AMAPÁ','AP');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6114','Ferreira Gomes','AMAPÁ','AP');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6122','Fruta de Leite','MINAS GERAIS','MG');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6130','Laranjal do Jari','AMAPÁ','AP');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6149','GAMELEIRAS','MINAS GERAIS','MG');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6157','Santana','AMAPÁ','AP');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6165','Glaucilândia','MINAS GERAIS','MG');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6173','Tartarugalzinho','AMAPÁ','AP');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6190','São Geraldo do Araguaia','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6203','GOIANA','MINAS GERAIS','MG');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6211','Ipixuna do Pará','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6238','Ulianopolis','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6254','Breu Branco','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6270','Goianésia do Pará','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6297','Novo Repartimento','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6300','JAPONVAR','MINAS GERAIS','MG');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6319','Jacareaçanga','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6327','JENIPAPO DE MINAS','MINAS GERAIS','MG');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6335','Novo Progresso','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6343','JOSÉ GONÇALVES DE MINAS','MINAS GERAIS','MG');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6351','Trairão','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6378','TERRA SANTA','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6394','Brasil Novo','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6408','JUVENILIA','MINAS GERAIS','MG');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6416','Vitória do Xingu','PARÁ','PA');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6424','LEME DO PRADO','MINAS GERAIS','MG');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6432','Acrelândia','ACRE','AC');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6459','Bujari','ACRE','AC');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6467','LUISLANDIA','MINAS GERAIS','MG');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6475','Capixaba','ACRE','AC');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6483','Mário Campos','MINAS GERAIS','MG');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6491','Porto Acre','ACRE','AC');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6505','MARTINS SOARES','MINAS GERAIS','MG');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6513','Epitaciolândia','ACRE','AC');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6530','Jordão','ACRE','AC');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6556','Marechal Thaumaturgo','ACRE','AC');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6564','NAQUE','MINAS GERAIS','MG');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6572','Porto Walter','ACRE','AC');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6599','Rodrigues Alves','ACRE','AC');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6602','NINHEIRA','MINAS GERAIS','MG');
INSERT INTO Municipio(ativo,id,nome,nome_uf,sigla_uf) VALUES ('1','6610','Santa Rosa','ACRE','AC');
