INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('1','EMPRESÁRIO INDIVIDUAL','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('2','SOCIEDADE EMPRESÁRIA LIMITADA','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('3','SOCIEDADE ANÔNIMA','0');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('4','COOPERATIVA','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('5','SOCIEDADE EMPRESÁRIA EM NOME COLETIVO','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('6','SOCIEDADE EM COMANDITA SIMPLES','0');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('7','SOCIEDADE CAPITAL INDÚSTRIA','0');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('8','SOCIEDADE EMPRESÁRIA EM COMANDITA POR AÇÕES','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('9','SOCIEDADE DE ECONOMIA MISTA','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('10','FUNDAÇÃO PRIVADA','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('11','SOCIEDADE CIVIL SEM FINS LUCRATIVOS E/OU UTILIDADE PUBLICA','0');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('12','SOCIEDADES CIVIS','0');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('13','EMPRESA PÚBLICA','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('14','ESTABELECIMENTO, NO BRASIL, DE SOCIEDADE ESTRANGEIRA','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('15','AUTARQUIAS E FUNDAÇÕES PÚBLICAS','0');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('16','ÓRGÃO PÚBLICO','0');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('17','DECISÃO JUDICIAL','0');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('18','SOCIEDADE SIMPLES PURA','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('19','SOCIEDADE SIMPLES LIMITADA','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('20','SOCIEDADE SIMPLES EM NOME COLETIVO','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('21','SOCIEDADE SIMPLES EM COMANDITA SIMPLES','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('22','SOCIEDADE EMPRESÁRIA EM COMANDITA SIMPLES','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('23','ASSOCIAÇÃO PRIVADA','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('24','EMPREENDEDOR INDIVIDUAL - LC 123, DE 2006 -','0');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('25','EMPRESA INDIVIDUAL DE RESPONSABILIDADE LIMITADA (DE NATUREZA EMPRESÁRIA)','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('26','SERVIÇO SOCIAL AUTÔNOMO','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('27','ÓRGÃO PÚBLICO DO PODER EXECUTIVO FEDERAL','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('28','ÓRGÃO PÚBLICO DO PODER EXECUTIVO ESTADUAL','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('29','ÓRGÃO PÚBLICO DO PODER EXECUTIVO MUNICIPAL','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('30','ÓRGÃO PÚBLICO DO PODER LEGISLATIVO FEDERAL','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('31','ÓRGÃO PÚBLICO DO PODER LEGISLATIVO ESTADUAL','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('32','ÓRGÃO PÚBLICO DO PODER LEGISLATIVO MUNICIPAL','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('33','ÓRGÃO PÚBLICO DO PODER JUDICIÁRIO FEDERAL','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('34','ÓRGÃO PÚBLICO DO PODER JUDICIÁRIO ESTADUAL','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('35','AUTARQUIA FEDERAL','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('36','AUTARQUIA ESTADUAL OU DO DISTRITO FEDERAL','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('37','AUTARQUIA MUNICIPAL','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('38','FUNDAÇÃO FEDERAL','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('39','FUNDAÇÃO ESTADUAL OU DO DISTRITO FEDERAL','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('40','FUNDAÇÃO MUNICIPAL','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('41','ÓRGÃO PÚBLICO AUTÔNOMO FEDERAL','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('42','ÓRGÃO PÚBLICO AUTÔNOMO ESTADUAL OU DO DISTRITO FEDERAL','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('43','ÓRGÃO PÚBLICO AUTÔNOMO MUNICIPAL','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('44','COMISSÃO POLINACIONAL','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('45','FUNDO PÚBLICO','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('46','ASSOCIAÇÃO PÚBLICA','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('47','SOCIEDADE ANÔNIMA ABERTA','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('48','SOCIEDADE ANÔNIMA FECHADA','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('49','SOCIEDADE EM CONTA DE PARTICIPAÇÃO','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('50','CONSÓRCIO DE SOCIEDADES','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('51','GRUPO DE SOCIEDADES','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('52','ESTABELECIMENTO, NO BRASIL, DE FUNDAÇÃO OU ASSOCIAÇÃO ESTRANGEIRAS','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('53','EMPRESA DOMICILIADA NO EXTERIOR','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('54','CLUBE/FUNDO DE INVESTIMENTO','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('55','EMPRESA BINACIONAL','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('56','CONSÓRCIO DE EMPREGADORES','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('57','CONSÓRCIO SIMPLES','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('58','EMPRESA INDIVIDUAL DE RESPONSABILIDADE LIMITADA (DE NATUREZA SIMPLES)','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('59','SERVIÇO NOTORIAL E REGISTRAL (CARTÓRIO)','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('60','CONDOMÍNIO EDILÍCIO','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('61','COMISSÃO DE CONCILIAÇÃO PRÉVIA','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('62','ENTIDADE DE MEDIAÇÃO E ARBITRAGEM','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('63','PARTIDO POLÍTICO','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('64','ENTIDADE SINDICAL','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('65','FUNDAÇÃO OU ASSOCIAÇÃO DOMICILIADA NO EXTERIOR','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('66','ORGANIZAÇÃO RELIGIOSA','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('67','COMUNIDADE INDÍGENA','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('68','FUNDO PRIVADO','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('69','EMPRESA INDIVIDUAL IMOBILIÁRIA','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('70','CONTRIBUINTE INDIVIDUAL','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('71','CANDIDATO A CARGO POLÍTICO ELETIVO','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('72','ORGANIZAÇÃO INTERNACIONAL','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('73','REPRESENTAÇÃO DIPLOMÁTICA ESTRANGEIRA','1');
INSERT INTO NaturezaJuridica(id,descricao,ativo) VALUES ('74','OUTRAS INSTITUIÇÕES EXTRATERRITORIAIS','1');
